import uuid
from datetime import date, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from api.models.base import Base


class Attempt(Base):
    __tablename__ = "attempts"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    challenge_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    difficulty: Mapped[str | None] = mapped_column(String, nullable=True, index=True)
    passed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    xp_earned: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    hints_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    time_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # SHA-256 of the normalized solution. Used to detect copy-paste cheating
    # without storing the raw code. Nullable for backfill compatibility.
    solution_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    # Set when this submission's hash matches a passing submission from a
    # different user on the same challenge. Internal signal only — the user
    # is not informed and the attempt still records normally.
    flagged_duplicate: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )


class UserProgress(Base):
    __tablename__ = "user_progress"

    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    total_xp: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    level: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    streak_days: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_active: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    topics: Mapped[dict[str, int]] = mapped_column(
        JSON, nullable=False, default=dict, server_default=text("'{}'")
    )
    last_reengagement_email_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_friend_digest_email_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Distinct from streak_days. The activity streak counts any submission;
    # daily_streak_days only ticks up when the user passes the daily challenge
    # on a UTC calendar day. Harder to maintain, stronger retention signal.
    daily_streak_days: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    last_daily_solved_date: Mapped[date | None] = mapped_column(Date, nullable=True)


class Challenge(Base):
    """Canonical challenge bank row. Read at request time by the engine.
    Seeded from engine_core.challenge_bank for the initial roster; new
    rows are written by the proposed_challenges approval flow."""

    __tablename__ = "challenges"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    topic: Mapped[str] = mapped_column(String, nullable=False, index=True)
    difficulty: Mapped[str] = mapped_column(String, nullable=False, index=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    prompt: Mapped[str] = mapped_column(String, nullable=False)
    constraints: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    examples: Mapped[list[dict[str, str]]] = mapped_column(JSON, nullable=False)
    source: Mapped[str] = mapped_column(
        String, nullable=False, default="seed", server_default=text("'seed'")
    )
    proposed_challenge_id: Mapped[str | None] = mapped_column(String, nullable=True)
    # Calibrator predictions, captured at the point a challenge enters the
    # bank. Nullable for legacy seed rows that pre-date the calibrator.
    predicted_solve_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    predicted_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    prediction_model: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class ProposedChallenge(Base):
    """A challenge candidate generated by the AI pipeline awaiting human
    review. Approved candidates are inserted directly into the challenges
    table by the review CLI."""

    __tablename__ = "proposed_challenges"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    topic: Mapped[str] = mapped_column(String, nullable=False)
    difficulty: Mapped[str] = mapped_column(String, nullable=False)
    title: Mapped[str] = mapped_column(String, nullable=False)
    prompt: Mapped[str] = mapped_column(String, nullable=False)
    constraints: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    examples: Mapped[list[dict[str, str]]] = mapped_column(JSON, nullable=False)
    sample_solution: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="pending", server_default=text("'pending'")
    )
    generation_model: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    reviewer_notes: Mapped[str | None] = mapped_column(String, nullable=True)
    approved_challenge_id: Mapped[str | None] = mapped_column(String, nullable=True)
    predicted_solve_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    predicted_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    prediction_model: Mapped[str | None] = mapped_column(String, nullable=True)


class DailyChallenge(Base):
    __tablename__ = "daily_challenges"

    date: Mapped[date] = mapped_column(Date, primary_key=True)
    challenge_id: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class BossRushRun(Base):
    """One Boss Rush attempt: 3 boss-tier challenges, 3 lives, all-or-
    nothing ending. status transitions in_progress -> completed (all 3
    passed) or wiped (lives hit 0)."""

    __tablename__ = "boss_rush_runs"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="in_progress", server_default=text("'in_progress'")
    )
    # Three challenge ids picked at start. Frozen for the run's life so a
    # mid-run bank change can't shift the gauntlet under the player.
    challenge_ids: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    # Equals the number of problems already passed (0..3). Doubles as the
    # "which problem are we on" pointer until current_index == 3.
    current_index: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    lives_remaining: Mapped[int] = mapped_column(
        Integer, nullable=False, default=3, server_default=text("3")
    )
    attempts_total: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    # Awarded once on terminal status — null while in_progress.
    xp_awarded: Mapped[int | None] = mapped_column(Integer, nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    ended_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class InterviewSession(Base):
    """One mock-interview run. Created when the user clicks Start, completed
    when they click End and the post-mortem is synthesized. Single-problem
    in Phase 1; Phase 2 will add a sequence (warmup -> main -> follow-up)."""

    __tablename__ = "interview_sessions"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="in_progress", server_default=text("'in_progress'")
    )
    challenge_id: Mapped[str] = mapped_column(String, nullable=False)
    topic: Mapped[str | None] = mapped_column(String, nullable=True)
    difficulty: Mapped[str | None] = mapped_column(String, nullable=True)
    solution: Mapped[str | None] = mapped_column(String, nullable=True)
    transcript: Mapped[str | None] = mapped_column(String, nullable=True)
    language: Mapped[str | None] = mapped_column(String, nullable=True)
    time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    overall_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    feedback: Mapped[str | None] = mapped_column(String, nullable=True)
    strengths: Mapped[str | None] = mapped_column(String, nullable=True)
    improvements: Mapped[str | None] = mapped_column(String, nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    ended_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class ReviewSchedule(Base):
    __tablename__ = "review_schedule"
    __table_args__ = (
        UniqueConstraint("user_id", "challenge_id", name="uq_review_user_challenge"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    challenge_id: Mapped[str] = mapped_column(String, nullable=False)
    ease_factor: Mapped[float] = mapped_column(Float, nullable=False, default=2.5)
    interval_days: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    repetitions: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    due_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    last_quality: Mapped[int | None] = mapped_column(Integer, nullable=True)
    last_reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
